###
POST localhost:8080/api/v1/admin/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MzQwMDM4NjYsInBob25lIjoiKzk5ODk5MTIwNTU3NyIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzM1MDQzMDk1LCJpc3MiOiJZb3V0dWJlIn0.3UT9CdfhhEGUPnuZb1E-FF-OSapBnmyavIC8cCwZLXdx3p-4Gbq44WP4Slj--g5_zJn1xSLmT6ds2EN6uLKTKg

{
  "name": "techer",
  "surname": "teacher",
  "phone": "+998993331122",
  "password": "12345",
  "role": "ROLE_TEACHER"
}

###
PUT localhost:8080/api/v1/admin/update/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjM1NTI5OTIsInBob25lIjoiKzk5ODk5MTIwNTU3NyIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzIzNjM5MzkyLCJpc3MiOiJZb3V0dWJlIn0.gCWUGQovPDwpGXtDMblLOnTCxGCygrlV5yuObSw_L-c5rq9gl8RNOkJzx7jECzsRhn71e9hcgIMc16C0xFoInA

{
  "password": "12322"
}

###
GET localhost:8080/api/v1/admin/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MzM5NDA4NjIsInBob25lIjoiKzk5ODk5MTIyMTIwMiIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MzQ5ODAwOTEsImlzcyI6IllvdXR1YmUifQ.LwxHsvV3G4r8rxIlCMD0rrcHWbPNde_ft89cstf94ESzy0iUDorcJE-zCJoj5xlzy8tz4AGWPahEdqNq8zKLOA

###
GET localhost:8080/api/v1/admin/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MzM5NDEwMzQsInBob25lIjoiKzk5ODk5MTIwNTU3NyIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzM0OTgwMjYyLCJpc3MiOiJZb3V0dWJlIn0.3v6_KsWSeHa2evM_zOQIIvuW4Zg7hJzVCrlz4eHryu4puXavqovxE_3UjP2GFViXBSq_ZhZXwQEnof3FmWEq-w


###
POST localhost:8080/api/v1/admin/filter?page=1&size=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjM3MTYwMjgsInBob25lIjoiKzk5ODk5MTIwNTU3NyIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzIzODAyNDI4LCJpc3MiOiJZb3V0dWJlIn0.YRn_abUv6-Z8ZMXHthOuBk4M8aqvTa1ukbbtV24xxcpc9u2fRJFRlSENc_-XBi7wYBvtUmgpu5750Vt89242qw

{
  "phone": "+9989912212023"
}



